export const PAYMENT_METHOD_LABELS: Record<string, string> = {
  bca_va: "BCA Virtual Account",
  bni_va: "BNI Virtual Account",
  bri_va: "BRI Virtual Account",
  permata_va: "Permata Virtual Account",
  mandiri_va: "Mandiri Virtual Account",
  cimb_va: "CIMB Niaga Virtual Account",
  bsi_va: "BSI Virtual Account",
  bjb_va: "BJB Virtual Account",
  dana: "DANA",
  linkaja: "LinkAja",
  ovo: "OVO",
  jenius: "Jenius Pay",
  other_va: "Virtual Account",
  bank_transfer: "Virtual Account",
  echannel: "Mandiri Bill Payment",
  gopay: "GoPay",
  shopeepay: "ShopeePay",
  qris: "QRIS",
  indomaret: "Indomaret",
  alfamart: "Alfamart",
  credit_card: "Kartu Kredit",
  cstore: "Convenience Store",
};
