-- ============================================================
-- NZO Industries — data katalog awal (Fase 3)
-- Pohon kategori sparepart + merek/model kendaraan populer Indonesia.
-- Di-generate dari src/lib/import/{categories,vehicles}.ts (sumber kebenaran);
-- tahun produksi perkiraan, dirapikan admin di Fase 8. Idempotent.
-- ============================================================

select set_config('nzo.skip_audit', 'on', true);

insert into public.categories (name, slug, parent_id, is_automotive, is_active, sort_order) values
  ('Motor', 'motor', null, true, true, 1),
  ('Mobil', 'mobil', null, true, true, 2),
  ('Non-otomotif', 'non-otomotif', null, false, true, 3),
  ('Belum dikategorikan', 'belum-dikategorikan', null, true, false, 4)
on conflict (slug) do update set
  name = excluded.name, parent_id = null, is_automotive = excluded.is_automotive,
  is_active = excluded.is_active, sort_order = excluded.sort_order;

insert into public.categories (name, slug, parent_id, is_automotive, is_active, sort_order)
select c.name, c.slug, p.id, c.is_automotive, c.is_active, c.sort_order
from (values
  ('motor', 'Mesin', 'mesin-motor', true, true, 1),
  ('motor', 'Pengereman', 'rem-motor', true, true, 2),
  ('motor', 'Kelistrikan & lampu', 'lampu-motor', true, true, 3),
  ('motor', 'Suspensi & kaki-kaki', 'suspensi-motor', true, true, 4),
  ('motor', 'Transmisi, CVT & kopling', 'transmisi-motor', true, true, 5),
  ('motor', 'Karburator & injeksi', 'bahan-bakar-motor', true, true, 6),
  ('motor', 'Filter', 'filter-motor', true, true, 7),
  ('motor', 'Oli & cairan', 'oli-motor', true, true, 8),
  ('motor', 'Ban, velg & roda', 'ban-velg-motor', true, true, 9),
  ('motor', 'Knalpot', 'knalpot-motor', true, true, 10),
  ('motor', 'Baut, mur & seal', 'baut-seal-motor', true, true, 11),
  ('motor', 'Body & aksesoris', 'aksesoris-motor', true, true, 12),
  ('mobil', 'Mesin', 'mesin-mobil', true, true, 1),
  ('mobil', 'Pengereman', 'rem-mobil', true, true, 2),
  ('mobil', 'Kelistrikan & lampu', 'lampu-mobil', true, true, 3),
  ('mobil', 'Kaki-kaki', 'kaki-kaki-mobil', true, true, 4),
  ('mobil', 'Filter', 'filter-mobil', true, true, 5),
  ('mobil', 'Oli & cairan', 'oli-mobil', true, true, 6),
  ('mobil', 'Wiper', 'wiper', true, true, 7),
  ('mobil', 'Body & interior', 'aksesoris-interior', true, true, 8),
  ('non-otomotif', 'Perawatan & kebersihan', 'perawatan-kebersihan', false, true, 1),
  ('non-otomotif', 'Peralatan', 'peralatan', false, true, 2),
  ('non-otomotif', 'Lainnya', 'lainnya', false, true, 3)
) as c(parent_slug, name, slug, is_automotive, is_active, sort_order)
join public.categories p on p.slug = c.parent_slug
on conflict (slug) do update set
  name = excluded.name, parent_id = excluded.parent_id, is_automotive = excluded.is_automotive,
  is_active = excluded.is_active, sort_order = excluded.sort_order;

insert into public.vehicle_makes (name, slug, vehicle_type, sort_order) values
  ('Honda', 'honda', 'motorcycle', 1),
  ('Yamaha', 'yamaha', 'motorcycle', 2),
  ('Suzuki', 'suzuki', 'motorcycle', 3),
  ('Kawasaki', 'kawasaki', 'motorcycle', 4),
  ('Vespa', 'vespa', 'motorcycle', 5),
  ('Toyota', 'toyota', 'car', 1),
  ('Honda', 'honda', 'car', 2),
  ('Daihatsu', 'daihatsu', 'car', 3),
  ('Suzuki', 'suzuki', 'car', 4),
  ('Mitsubishi', 'mitsubishi', 'car', 5)
on conflict (slug, vehicle_type) do update set name = excluded.name, sort_order = excluded.sort_order;

insert into public.vehicle_models (make_id, name, slug, vehicle_type, year_start, year_end)
select mk.id, m.name, m.slug, m.vtype::public.vehicle_type, m.y1, m.y2
from (values
  ('honda', 'motorcycle', 'BeAT', 'beat', 2008, null::smallint),
  ('honda', 'motorcycle', 'Vario 160', 'vario-160', 2022, null::smallint),
  ('honda', 'motorcycle', 'Vario 150', 'vario-150', 2015, 2022),
  ('honda', 'motorcycle', 'Vario 125', 'vario-125', 2012, null::smallint),
  ('honda', 'motorcycle', 'Vario 110', 'vario-110', 2006, 2019),
  ('honda', 'motorcycle', 'Scoopy', 'scoopy', 2010, null::smallint),
  ('honda', 'motorcycle', 'Spacy', 'spacy', 2011, 2018),
  ('honda', 'motorcycle', 'Genio', 'genio', 2019, null::smallint),
  ('honda', 'motorcycle', 'PCX 160', 'pcx-160', 2021, null::smallint),
  ('honda', 'motorcycle', 'PCX 150', 'pcx-150', 2014, 2020),
  ('honda', 'motorcycle', 'ADV 160', 'adv-160', 2022, null::smallint),
  ('honda', 'motorcycle', 'ADV 150', 'adv-150', 2019, 2022),
  ('honda', 'motorcycle', 'Supra X 125', 'supra-x-125', 2005, null::smallint),
  ('honda', 'motorcycle', 'Supra X', 'supra-x', 1997, 2005),
  ('honda', 'motorcycle', 'Astrea Grand', 'astrea-grand', 1991, 2001),
  ('honda', 'motorcycle', 'Revo', 'revo', 2007, null::smallint),
  ('honda', 'motorcycle', 'Blade', 'blade', 2008, 2018),
  ('honda', 'motorcycle', 'Sonic 150R', 'sonic-150r', 2015, null::smallint),
  ('honda', 'motorcycle', 'CS1', 'cs1', 2008, 2012),
  ('honda', 'motorcycle', 'CB150R', 'cb150r', 2012, null::smallint),
  ('honda', 'motorcycle', 'CBR150R', 'cbr150r', 2002, null::smallint),
  ('honda', 'motorcycle', 'CBR250RR', 'cbr250rr', 2016, null::smallint),
  ('honda', 'motorcycle', 'CRF150L', 'crf150l', 2017, null::smallint),
  ('honda', 'motorcycle', 'MegaPro', 'megapro', 1999, 2018),
  ('honda', 'motorcycle', 'Tiger', 'tiger', 1993, 2013),
  ('honda', 'motorcycle', 'Verza', 'verza', 2013, 2021),
  ('honda', 'motorcycle', 'Kharisma', 'kharisma', 2003, 2005),
  ('honda', 'motorcycle', 'GL Pro', 'gl-pro', 1985, 2005),
  ('honda', 'motorcycle', 'CB100', 'cb100', 1971, 1990),
  ('honda', 'motorcycle', 'Win 100', 'win-100', 1984, 2004),
  ('yamaha', 'motorcycle', 'NMAX', 'nmax', 2015, null::smallint),
  ('yamaha', 'motorcycle', 'Aerox 155', 'aerox-155', 2016, null::smallint),
  ('yamaha', 'motorcycle', 'Lexi', 'lexi', 2018, null::smallint),
  ('yamaha', 'motorcycle', 'XMAX', 'xmax', 2017, null::smallint),
  ('yamaha', 'motorcycle', 'FreeGo', 'freego', 2019, null::smallint),
  ('yamaha', 'motorcycle', 'Gear 125', 'gear-125', 2020, null::smallint),
  ('yamaha', 'motorcycle', 'Fazzio', 'fazzio', 2021, null::smallint),
  ('yamaha', 'motorcycle', 'Fino', 'fino', 2007, null::smallint),
  ('yamaha', 'motorcycle', 'Mio M3', 'mio-m3', 2014, null::smallint),
  ('yamaha', 'motorcycle', 'Mio Z', 'mio-z', 2015, 2019),
  ('yamaha', 'motorcycle', 'Mio J', 'mio-j', 2012, 2016),
  ('yamaha', 'motorcycle', 'Mio Soul GT', 'mio-soul-gt', 2012, null::smallint),
  ('yamaha', 'motorcycle', 'Mio Soul', 'mio-soul', 2010, 2012),
  ('yamaha', 'motorcycle', 'Mio Sporty', 'mio-sporty', 2003, 2012),
  ('yamaha', 'motorcycle', 'Nouvo', 'nouvo', 2002, 2013),
  ('yamaha', 'motorcycle', 'Xeon', 'xeon', 2010, 2015),
  ('yamaha', 'motorcycle', 'X-Ride', 'x-ride', 2013, null::smallint),
  ('yamaha', 'motorcycle', 'Jupiter MX King', 'jupiter-mx-king', 2015, null::smallint),
  ('yamaha', 'motorcycle', 'Jupiter MX', 'jupiter-mx', 2005, 2015),
  ('yamaha', 'motorcycle', 'Jupiter Z', 'jupiter-z', 2003, null::smallint),
  ('yamaha', 'motorcycle', 'Vega ZR', 'vega-zr', 2003, null::smallint),
  ('yamaha', 'motorcycle', 'F1ZR', 'f1zr', 1994, 2005),
  ('yamaha', 'motorcycle', 'Crypton', 'crypton', 1997, 2002),
  ('yamaha', 'motorcycle', 'RX-King', 'rx-king', 1983, 2009),
  ('yamaha', 'motorcycle', 'RX-Z', 'rx-z', 1985, 2009),
  ('yamaha', 'motorcycle', 'Alfa', 'alfa', 1981, 1995),
  ('yamaha', 'motorcycle', 'Scorpio', 'scorpio', 2001, 2017),
  ('yamaha', 'motorcycle', 'Byson', 'byson', 2010, 2019),
  ('yamaha', 'motorcycle', 'Vixion', 'vixion', 2007, null::smallint),
  ('yamaha', 'motorcycle', 'R15', 'r15', 2014, null::smallint),
  ('yamaha', 'motorcycle', 'R25', 'r25', 2014, null::smallint),
  ('yamaha', 'motorcycle', 'MT-15', 'mt-15', 2019, null::smallint),
  ('yamaha', 'motorcycle', 'MT-25', 'mt-25', 2015, null::smallint),
  ('yamaha', 'motorcycle', 'XSR 155', 'xsr-155', 2019, null::smallint),
  ('yamaha', 'motorcycle', 'WR155', 'wr155', 2019, null::smallint),
  ('suzuki', 'motorcycle', 'Satria F150', 'satria-f150', 2004, null::smallint),
  ('suzuki', 'motorcycle', 'Satria 2T', 'satria-2t', 1997, 2005),
  ('suzuki', 'motorcycle', 'Shogun', 'shogun', 1996, 2012),
  ('suzuki', 'motorcycle', 'Smash', 'smash', 2002, 2017),
  ('suzuki', 'motorcycle', 'Spin', 'spin', 2007, 2013),
  ('suzuki', 'motorcycle', 'Skywave', 'skywave', 2007, 2013),
  ('suzuki', 'motorcycle', 'Nex II', 'nex-ii', 2018, null::smallint),
  ('suzuki', 'motorcycle', 'Nex', 'nex', 2011, 2018),
  ('suzuki', 'motorcycle', 'Address', 'address', 2014, null::smallint),
  ('suzuki', 'motorcycle', 'Thunder 125', 'thunder-125', 2005, 2015),
  ('suzuki', 'motorcycle', 'GSX-R150', 'gsx-r150', 2017, null::smallint),
  ('suzuki', 'motorcycle', 'GSX-S150', 'gsx-s150', 2017, null::smallint),
  ('suzuki', 'motorcycle', 'RGR 150', 'rgr-150', 1990, 2003),
  ('suzuki', 'motorcycle', 'Tornado', 'tornado', 1996, 2003),
  ('suzuki', 'motorcycle', 'Crystal', 'crystal', 1992, 1997),
  ('suzuki', 'motorcycle', 'A100', 'a100', 1975, 1995),
  ('kawasaki', 'motorcycle', 'Ninja 250', 'ninja-250', 2008, null::smallint),
  ('kawasaki', 'motorcycle', 'Ninja 150 RR', 'ninja-150-rr', 1998, 2015),
  ('kawasaki', 'motorcycle', 'ZX-25R', 'zx-25r', 2020, null::smallint),
  ('kawasaki', 'motorcycle', 'Z250', 'z250', 2013, null::smallint),
  ('kawasaki', 'motorcycle', 'KLX 150', 'klx-150', 2009, null::smallint),
  ('kawasaki', 'motorcycle', 'D-Tracker 150', 'd-tracker-150', 2009, null::smallint),
  ('kawasaki', 'motorcycle', 'W175', 'w175', 2017, null::smallint),
  ('kawasaki', 'motorcycle', 'Athlete', 'athlete', 2009, 2013),
  ('kawasaki', 'motorcycle', 'Blitz', 'blitz', 2004, 2010),
  ('kawasaki', 'motorcycle', 'Kaze', 'kaze', 1996, 2006),
  ('kawasaki', 'motorcycle', 'Edge', 'edge', 2007, 2009),
  ('vespa', 'motorcycle', 'Vespa LX', 'lx', 2012, null::smallint),
  ('vespa', 'motorcycle', 'Vespa Sprint', 'sprint', 2014, null::smallint),
  ('vespa', 'motorcycle', 'Vespa Primavera', 'primavera', 2014, null::smallint),
  ('vespa', 'motorcycle', 'Vespa S', 's', 2012, null::smallint),
  ('vespa', 'motorcycle', 'Vespa GTS', 'gts', 2012, null::smallint),
  ('vespa', 'motorcycle', 'Vespa PX', 'px', 1977, null::smallint),
  ('toyota', 'car', 'Avanza', 'avanza', 2003, null::smallint),
  ('toyota', 'car', 'Kijang Innova Reborn', 'innova-reborn', 2016, null::smallint),
  ('toyota', 'car', 'Innova', 'innova', 2004, 2015),
  ('toyota', 'car', 'Kijang', 'kijang', 1977, 2004),
  ('toyota', 'car', 'Calya', 'calya', 2016, null::smallint),
  ('toyota', 'car', 'Agya', 'agya', 2013, null::smallint),
  ('toyota', 'car', 'Rush', 'rush', 2006, null::smallint),
  ('toyota', 'car', 'Fortuner', 'fortuner', 2005, null::smallint),
  ('toyota', 'car', 'Yaris', 'yaris', 2006, null::smallint),
  ('toyota', 'car', 'Vios', 'vios', 2003, null::smallint),
  ('honda', 'car', 'Brio', 'brio', 2012, null::smallint),
  ('honda', 'car', 'Jazz', 'jazz', 2003, 2021),
  ('honda', 'car', 'HR-V', 'hr-v', 2014, null::smallint),
  ('honda', 'car', 'Mobilio', 'mobilio', 2014, null::smallint),
  ('daihatsu', 'car', 'Xenia', 'xenia', 2004, null::smallint),
  ('daihatsu', 'car', 'Ayla', 'ayla', 2013, null::smallint),
  ('daihatsu', 'car', 'Sigra', 'sigra', 2016, null::smallint),
  ('daihatsu', 'car', 'Terios', 'terios', 2006, null::smallint),
  ('daihatsu', 'car', 'Gran Max', 'gran-max', 2007, null::smallint),
  ('daihatsu', 'car', 'Luxio', 'luxio', 2009, null::smallint),
  ('suzuki', 'car', 'Ertiga', 'ertiga', 2012, null::smallint),
  ('suzuki', 'car', 'Carry Pick Up', 'carry-pick-up', 2019, null::smallint),
  ('suzuki', 'car', 'Carry Futura', 'carry-futura', 1991, 2019),
  ('suzuki', 'car', 'Jimny', 'jimny', 1981, null::smallint),
  ('suzuki', 'car', 'Katana', 'katana', 1988, 2006),
  ('suzuki', 'car', 'APV', 'apv', 2004, null::smallint),
  ('suzuki', 'car', 'Swift', 'swift', 2005, 2017),
  ('suzuki', 'car', 'Karimun', 'karimun', 1999, null::smallint),
  ('mitsubishi', 'car', 'Xpander', 'xpander', 2017, null::smallint),
  ('mitsubishi', 'car', 'Pajero Sport', 'pajero-sport', 2008, null::smallint),
  ('mitsubishi', 'car', 'L300', 'l300', 1981, null::smallint),
  ('mitsubishi', 'car', 'Colt Diesel', 'colt-diesel', 1985, null::smallint)
) as m(make_slug, vtype, name, slug, y1, y2)
join public.vehicle_makes mk on mk.slug = m.make_slug and mk.vehicle_type = m.vtype::public.vehicle_type
on conflict (make_id, slug) do update set
  name = excluded.name, year_start = excluded.year_start, year_end = excluded.year_end;
